### ISSUE TITLE
Add version control to HGVS error dict

### ISSUE THREAD

**Issue by la60312** [PEDIA-Charite/PEDIA-workflow#21]
Add version number to HGVS error dict files, and add a file to track the version of HGVS error dict file.
Compare two number when we run the preprocessing. Only process the files with identical version.

**Comment by xiamaz** [comment]
Do you mean the version of the error dict itself or the algorithm version used to process the cases?

**Comment by la60312** [comment]
There should be a version in error dict file. This is modified by Tori or the others. Now, we send this file by email or the other way. It is difficult to know which one is the latest version. So we need to store the latest version number in a file. This file could be the file which stores all the version number of external files. Once Tori provides a new version of error dict file. We need to update this version in this file.
