### ISSUE TITLE
Fix missing gene name of pathogenic mutation gene

### ISSUE THREAD

**Issue by la60312** [PEDIA-Charite/PEDIA-workflow#22]
We have two problem with the pathogenic mutation gene. There are some cases with empty gene name of pathogenic mutation gene. Secondly, some gene names can't be found in the gene list.
The reason could be the different gene name of the same gene or the mutation was filtered out.
We could implement the same way with the one we did with HGVS code to fix the gene name in these cases.

This is the list of the case whose pathogenic mutation gene can be found in gene list.
problem with 130024 
problem with 123674
problem with 40536 
problem with 42112
problem with 77968 
problem with 53364 
problem with 46883 
Gene  is not found in case 107819
Gene is not found in case 164434
Gene is not found in case 106163
Gene is not found in case 221267

This is the list of the cases whose pathogenic mutation gene name is empty.
problem with 128548 
problem with 129586 
problem with 140809 
problem with 34230 
problem with 221325 
problem with 45255 
problem with 144481 
problem with 114186

**Comment by GSalma** [comment]
144481, 45255, 128548 : have to Gene Name entries, one is Empty and one contains gene name which is also present in geneList > PMM2, PTPN11 , KAT6B respectively.

for the Gene names that don't appear in the geneList, the ones I checked had a different transcript ID to their gene symbol in the genomic entries files. 
example : case 40536, "gene_symbol": "CASKIN1", "transcript": "NM_003036.3"
that transcript is for gene : SKI which does appear in geneList of this case. 

For case 130024, Gene Name entry is ERRC6L and in geneList it appears as it's synonym : ERRC6

ERRC6L
--




ERRC6L
--
