### ISSUE TITLE
Output all converted JSON files

### ISSUE THREAD

**Issue by la60312** [PEDIA-Charite/PEDIA-workflow#29]
We only have the converted JSON files now. Some cases are the testing cases with unknown diagnosis. They won't have genomic data. We need to process them and provide user with the PEDIA results. Therefore, please output every case which have suggested_syndrome list. You could output them to mapped folder just like the one in new_download branch.

**Comment by xiamaz** [comment]
do they have vcf data, some other sign, that they are test cases?

**Comment by la60312** [comment]
No, they will send blood sample to the NGS facility here. We don't have any information from F2G. Moreover, there are some cases with the diagnosis or disease-causing gene but without  HGVS code. I need those cases for another analysis. Therefore, you should output all the converted JSON files even though some cases are failed in QC. You should think they are different steps. Firstly, we mapped the disorder to genes. Then we run the QC to check their HGVS code.

**Comment by xiamaz** [comment]
Okay, I will reduce the checks on the json level and do most of the strict criteria on a case level (after hgvs mapping)

Still, currently mapping for chromosomal aberrations and other complex changes are not implemented (and not covered by PEDIA as far as I know).

should I just exclude these from hgvs generation?

Should I map these cases at all?

**Comment by la60312** [comment]
Just map all the cases

**Comment by xiamaz** [comment]
@GSalma Could you implement chromosomal mapping in hgvs?
