### ISSUE TITLE
strange behavior while generating VCF and config.yml

### ISSUE THREAD

**Issue by la60312** [PEDIA-Charite/PEDIA-workflow#35]
I think we change the behavior a little bit. I don't know if it affect the results. Max change the preprocess.py in https://github.com/PEDIA-Charite/PEDIA-workflow/commit/7154c8a6dc6283e1f80b952ab9a95a5d7eaec2d4
He removed this line.
```
cases = [case for case in cases if case.check()[0]]
```
And he added these lines instead.
```
if args.entry == "pheno" or args.entry == "convert":
+        old_jsons = convert_to_old_format(args, config_data, cases)
 +    else:
 +        old_jsons = None
 +
 +    if args.entry == "pheno" \
 +            or args.entry == "convert" \
 +            or args.entry == "qc":
 +        stats = quality_check_cases(args, config_data, cases, old_jsons)
 +        print(
 +            "== QC results ==\nPassed: {pass} Failed: {fail}".format(
 +                **stats)
 +        )
 +
 +    if args.entry == "pheno" \
 +            or args.entry == "convert" \
 +            or args.entry == "qc" \
 +            or args.entry == "vcf":
 +        cases = save_vcfs(config_data, cases)
 +        create_config()
 +

```
It seems like we generate the VCF for all cases based on the progress bar. Could you discuss it to check if there is something wrong?
```
== Phenomization of cases ==
Phenomization:  [####################] 2239/2239
== Mapping to old json format ==
Convert old:    [####################] 2239/2239
== Quality check ==
== QC results ==
Passed: 353 Failed: 1886
Generate VCFs:  [###                 ]  326/2239
```

**Comment by xiamaz** [comment]
This should not be an issue. VCF generation does not work without transcripts. The config is only generated from the output folder. If you check the preprocess.log, you will see a large number of entries for missing variants for vcf generation.

Nonetheless vcf files could be generated for cases that do not pass other criteria.

Is this an issue?

**Comment by jakobhertzberg** [comment]
Since the config is generated based on the output folder it includes VCF files of cases that do not pass other criteria. I think that is an issue for simulation.

**Comment by la60312** [comment]
I think it's this part. We based on the vcf file we generated in data/PEDIA/mutations/ to create config.yml. Is it correct? 
```
vcffiles = [file.split(".")[0] for file in os.listdir(vcffolder)]
singlefiles = [file.split(".")[0] for file in os.listdir(simvcffolder)]
testfiles = []
```

**Comment by la60312** [comment]
I will add it and test again.

**Comment by la60312** [comment]
@xiamaz @jakobhertzberg  I wonder if the report based on the QC by Jannovar or only bu mutalyzer.

**Comment by xiamaz** [comment]
@la60312 Currently only mutalyzer.

I am adding VCF generation errors right now

**Comment by la60312** [comment]
Passed QC or not is based on Jannovar not mutalyzer. Even if mutalyzer disagree with the HGVS code but Jannovar can convert it, we still say it is passed QC.

**Comment by la60312** [comment]
I added it back.

https://github.com/PEDIA-Charite/PEDIA-workflow/commit/007bc3b804e925c0f0715b26d94e70710f7f387d
