### ISSUE TITLE
Error in convert HGVS to VCF file

### ISSUE THREAD

**Issue by la60312** [PEDIA-Charite/PEDIA-workflow#45]
Could someone check this case 239518.json?
I got the error as following. It seems there is a error here.
```
lib/model/case.py
                if any(df.ALT == '<ERROR>'):
                    return(process.stderr)
```

```
/home/la60312/miniconda3/lib/python3.6/site-packages/pandas/core/ops.py:816: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)
Traceback (most recent call last):
  File "./preprocess.py", line 353, in <module>
    main()
  File "./preprocess.py", line 337, in main
    qc_cases = save_vcfs(args, config_data, qc_cases)
  File "./preprocess.py", line 215, in save_vcfs
    yield_vcf([v[1] for v in qc_cases.values() if v[0][0]])
  File "/home/la60312/pedia3/PEDIA-workflow/lib/visual.py", line 28, in progress_wrapper
    for i, res in enumerate(iter_func(*args, **kwds)):
  File "./preprocess.py", line 212, in yield_vcf
    case_obj.dump_vcf('data/PEDIA/mutations')
  File "/home/la60312/pedia3/PEDIA-workflow/lib/model/case.py", line 508, in dump_vcf
    self.vcf = self.create_vcf(path)
  File "/home/la60312/pedia3/PEDIA-workflow/lib/model/case.py", line 419, in create_vcf
    if any(df.ALT == '<ERROR>'):
  File "/home/la60312/miniconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 879, in wrapper
    res = na_op(values, other)
  File "/home/la60312/miniconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 818, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
```

**Comment by jakobhertzberg** [comment]
The error occurs because the ALT value after Jannovar parsed the HGVS code is NA and not as expected a string. NA is returned because the variant is a duplication. I will implement a fix and send a pull request.

**Comment by la60312** [comment]
It's weird. I checked it in UCSC genome browser. The ref is A or something, but the ref provided by Jannovar is N.

**Comment by jakobhertzberg** [comment]
The reference base is not given in the HGVS code. Jannovar seems not to be able to retrieve that information. Do you think you'll have a problem in simulation with the ambiguous reference base?

**Comment by la60312** [comment]
I haven't checked this. I found this problem last two weeks, but I didn't have time to check. Is it a bug or quite normal?

**Comment by jakobhertzberg** [comment]
I haven't had this problem yet but I think we just didn't have a HGVS that was given without a reference base and still got converted. Last week when I ran the pipeline I didn't have this case. It must have been uploaded quite recently. I can either accept the VCF with the ambiguous reference base and without an alternative base, add the reference base A in the error dictionary or discard the case.  Should I send you the single VCF file for this case to test it in simulation?

**Comment by la60312** [comment]
Yes, please. oh, I am not saying this case. I found a case with reference N before. I forgot which one. But there is nothing wrong(no exception raised) in the simulation.
