### ISSUE TITLE
Typo in jsonToTable.py

### ISSUE THREAD

**Issue by la60312** [PEDIA-Charite/PEDIA-workflow#8]
In jsonToTable.py, there are typos when we want to assign the higher feature value between the current gene and previous one. We used 'featureScore' in the maximum function for all score. Moreover, we didn't assign boqa score, and we assigned boqa score to gestalt score.
```
featureScore = max(featureScore,value["feature_score"])
caddPhredScore = max(featureScore,value["cadd_phred_score"])
combinedScore = max(featureScore,value["combined_score"])
caddRawSscore = max(featureScore,value["cadd_raw_score"])
gestaltScore = max(featureScore,value["boqa_score"])
phenoScore = max(featureScore,value["pheno_score"])
```

**Comment by visze** [comment]
:-) Thx for finding the bug!

Do you handle this, because you assigned it to you or should I do this?

**Comment by la60312** [comment]
Yes, I will push a patch later.
